# timezone: America/New_York
# center: 37.5021, -80.1042
# radius: 30.0
# state: VA
# county: Craig
#
# Restricted to Craig County, VA only.
New Castle  # 37.5001, -80.1109 (0.4 mi)
Paint Bank  # 37.5690, -80.2620 (9.8 mi)
